### PR TITLE
AUTHORIZATION SERVICE/AUTH-353: Update Naming to Adhere to New Names/Abbreviations

### PR DESCRIPTION
**Pull request by aymanthefirst**

### CODE REVIEW

**Comment by jottley** [comment]
@aymanthefirst The JIRA ticket for this was closed last November.  Should the JIRA be reopened? @melahn said when it was closed that an MMF needed to be created to address the work.

**Comment by melahn** [comment]
We should not be using AIMS for the reason @jottley mentioned.  

The old acroynm (AIS) is also wrong as it is now used by Alfresco Intelligence Services.  I would like to spell out 'Alfresco Identity Service' instead of using acronyms.   Since we should not use this branch tied to a closed issue.Suggest a separate branch for that or just make the change in master.

**Comment by aymanthefirst** [comment]
So is it OK for me to delete this PR? It doesn't have much in it anyway.

**Comment by melahn** [comment]
@aymanthefirst yes, you can delete it

**Pull request closed without merging**
