### PR TITLE
DEPLOY-686: Updated ACS chart version to 3.0.0

### PR DESCRIPTION
**Pull request by ehardon**

### CODE REVIEW

**Comment by montgolfiere** [comment]
Did you mean 2.0.0 ( https://github.com/Alfresco/acs-deployment/releases/2.0.0 ) for ACS 6.1.0 ?

https://github.com/Alfresco/acs-deployment/blob/master/docs/helm-versioning.md

**Comment by ehardon** [comment]
> Did you mean 2.0.0 for ACS 6.1.0 ?
> 
> https://github.com/Alfresco/acs-deployment/blob/master/docs/helm-versioning.md
> 
> * https://github.com/Alfresco/acs-deployment/releases/2.0.0
> * https://github.com/Alfresco/acs-deployment-aws/releases/2.0.0

@montgolfiere Unfortunately the 2.0.0 release contains Digital Workspace 1.0.0 and we need the 1.1.0 version (this version uses the Identity Service) and this is why we picked 3.0.0 that we found here: https://github.com/Alfresco/charts/blob/master/incubator/alfresco-content-services-3.0.0.tgz

**Comment by montgolfiere** [comment]
Hmm - does anyone know which repo / tag / build creates these charts / versions ?

Is this still valid https://github.com/Alfresco/acs-deployment/blob/master/docs/helm-versioning.md ?

**Comment by melahn** [comment]
@montgolfiere The purpose of this issue was to pull in a version of ACS that uses ADW 1.1 so we have 
a working configuration that uses IDS.   That's been done by including the ACS 3.0 chart.   If/when there's a 2.x.x chart that uses ADW 1.1 we can consider using that instead.   That probably would make more sense if the ACS 2.x.x chart includes ACS 6.1.1.

**Pull request merged**
