### PR TITLE
Document updates for supported EKS regions

### PR DESCRIPTION
**Pull request by proth1**
adding Ohio to the regions currently available.

### CODE REVIEW

**Comment by derekhulley** [comment]
Please pull #89 onto this change and update it to be descriptive.
When approved, please use "Squash and Merge"

**Comment by proth1** [comment]
What does "Squash and Merge" Mean and how do I do it?

**Comment by proth1** [comment]
@svidrascu if don't support new regions as they become available because we have work to do then we should not have the sentence and the link that refers a customer to and look at the current regions supporting EKS.

**Comment by derekhulley** [comment]
Rather than create a fixed list of regions, we should have a list of regions in which it does work AS WELL AS the means to discover new regions i.e. what does a region need to have.
We do not have resources to check all regions ourselves, so the region prerequisites should be explained.
Referring to @anxumalo for suggested text.

**Comment by svidrascu** [comment]
@proth1 I have modified this readme to be much clearer in our statement here. And also opened an additional PR on the source repo that is setting the limitations. 
https://github.com/Alfresco/acs-deployment-aws/pull/31

Thank you very much for your contribution and for spotting this issue.
Please feel free to open if there are any more issues with this.

**Pull request closed without merging**
